# See https://rust-lang.github.io/rustup/overrides.html for details on how this file works
# and how you can override the choices made herein.
#
# Note that UniFFI also sets their own toolchain (see https://github.com/mozilla/uniffi-rs/blob/main/rust-toolchain.toml).
# We will attempt to track stable unless we find that this breaks something.
# The iOS targets are easy and well-known, but the Android targets take a bit more work to deduce.
# We have drawn our list from https://github.com/mozilla/rust-android-gradle.

[toolchain]
channel = "1.92.0"
targets = [
    # macOS
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",

    # Linux (musl for static linking)
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",

    # Linux (gnu for dynamic linking)
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",

]
components = ["clippy", "rustfmt"]
